# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: rent_a_ride_development

test:
  <<: *default
  database: rent_a_ride_test

production:
  <<: *default
  database: rent_a_ride_production
  username: rent_a_ride
  password: <%= ENV['RENT_A_RIDE_DATABASE_PASSWORD'] %>
